
spring:
  datasource:
    username: root
    password: n20010907
    url: jdbc:mysql://localhost:3306/project
    driver-class-name: com.mysql.cj.jdbc.Driver

    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      mvc:
        throw-exception-if-no-handler-found: true
      web:
        resources:
          add-mappings: false

server:
  port: 8181